Update arguments.js
I have tried to run this example, but I got the following error message:

{
    "message": "Command failed: \nmodule.js:340\n    throw err;\n          ^\nError: Cannot find module '../lib/index'\n    at Function.Module._resolveFilename (module.js:338:15)\n    at Function.Module._load (module.js:280:25)\n    at Module.require (module.js:362:17)\n    at require (module.js:378:17)\n    at Object. (/home/node/tmp/2ebf54f9-e74a-40c8-8a22-f31aca2c9e70:9:15)\n    at Module._compile (module.js:449:26)\n    at Object.Module._extensions..js (module.js:467:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Module.runMain (module.js:492:10)\n"
}

After changing required module by 'tubesio'. It works well.